### ISSUE TITLE
Laser power control

### ISSUE THREAD

**Issue by iandobbie** [Gurdon-Super-Res-Lab/Microscope-Control#6]
I think that the laser power control should have some abstraction so we dont have to have a whole new VI for different arrangements. Maybe a laser-power notifier that then is configured to control the AOTF or the laser directly on a line by line basis with a config file.

**Comment by OtherEdward** [comment]
I have added two key VIs in "Microscope-Control\Microscope Modules\Laser Control" to address this. First, the "Laser Device Control.vi" is setup to communicate directly with the lasers (set laser power, turn emission on/off). Second, "Laser Power Control.vi" allows control of the laser power into the microscope. Each laser can be set to use a different control type (direct, AOTF or external). There is now a "Laser Power Control Messenger.vi" for other modules to turn on/off and control power for all lasers.
